name: Run tests

on: push

steps:
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.9
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
      pip install -e .
  - name: Ensure browsers are installed
    run: python -m playwright install
  - name: Install operating system dependencies
    run: python -m playwright install-deps
  - name: Run your tests
    run: pytest