name: Run tests

on: push

env:
  ENVIRONMENT: gha

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/ms-playwright/
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          python -m spacy download en_core_web_sm
          pip install -e .
      - name: Ensure browsers are installed
        run: python -m playwright install
      - name: Install operating system dependencies
        run: python -m playwright install-deps
      - name: Start Streamlit
        run: >-
          cd examples && \
          streamlit run 01_out-of-the-box.py \
          --server.port 8989 \
          --server.headless true \
          &
      - name: Run your tests
        run: cd .. && pytest
      - name: Cleanup / Kill streamlit
        run: kill %1
