name: Run tests

on: push

env:
  ENVIRONMENT: gha

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      streamlit_app:
        # Docker Hub image
        image: ghcr.io/${{ github.actor }}/${{ github.repository }}:release
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 8989:8989
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/ms-playwright/
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          python -m spacy download en_core_web_sm
          pip install -e .
      - name: Ensure browsers are installed
        run: python -m playwright install
      - name: Install operating system dependencies
        run: python -m playwright install-deps
      - name: Run your tests
        run: pytest